### ISSUE TITLE
import fails

### ISSUE THREAD

**Issue by streetdogg** [Jumperr-labs/hci-protocol#1]
When I try to do an import I see the following:

```
>>> from hci_protocol.hci_protocol import HciPacket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hci_protocol/hci_protocol.py", line 67, in <module>
    "payload" / Array(this.length, Byte),
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 1883, in __init__
    self.subcons = mergefields(*subcons)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 161, in mergefields
    result.extend(select(sc))
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 153, in select
    return select(sc.subcon)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 156, in select
    raise ConstructError("Embedding only works with: Struct Sequence FocusedSeq Union LazyStruct")
construct.core.ConstructError: Embedding only works with: Struct Sequence FocusedSeq Union LazyStruct
```

I am trying to find a fix for this but meanwhile if you could take a look.

**Comment by tazle** [comment]
Seems to be incompatibility with construct 2.9. 2.8.22 works.
